# Generated by Django 5.2.1 on 2025-05-10 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='dormitory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dormitories', to='dormitories.dormitory'),
        ),
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='dormitories.floor'),
        ),
    ]
