# Generated by Django 5.2.1 on 2025-05-11 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_alter_dormitorysubscription_created_by_and_more'),
        ('students', '0002_alter_application_student_alter_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentbystudent',
            name='transaction_id',
        ),
        migrations.AlterField(
            model_name='subscriptionforstudent',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='students.student'),
        ),
    ]
